# Generated by Django 5.1.11 on 2025-07-12 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Question text')),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('boolean', 'Yes/No'), ('checklist', 'Checklist'), ('radio', 'Radio'), ('select', 'Select')], default='text', help_text='Type of question', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active')),
                ('options', models.JSONField(blank=True, help_text='Options for select/radio/checklist questions', null=True)),
                ('visible_if', models.JSONField(blank=True, help_text='Conditions for when this question should be visible', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the question set', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the question set')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this question set')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this version is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Set',
                'verbose_name_plural': 'Question Sets',
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSetQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the question within the set')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this question is required in this set')),
                ('overrides', models.JSONField(blank=True, help_text='Optional overrides for question text, options, or conditional logic', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(help_text='Question in this set', on_delete=django.db.models.deletion.CASCADE, related_name='question_set_questions', to='questionnaire.question')),
                ('question_set', models.ForeignKey(help_text='Question set this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='question_set_questions', to='questionnaire.questionset')),
            ],
            options={
                'verbose_name': 'Question Set Question',
                'verbose_name_plural': 'Question Set Questions',
                'ordering': ['question_set', 'order'],
                'unique_together': {('question_set', 'question')},
            },
        ),
        migrations.AddField(
            model_name='questionset',
            name='questions',
            field=models.ManyToManyField(help_text='Questions in this question set', related_name='question_sets', through='questionnaire.QuestionSetQuestion', to='questionnaire.question'),
        ),
        migrations.AlterUniqueTogether(
            name='questionset',
            unique_together={('name', 'version')},
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.JSONField(help_text='Condition that must be met for the dependent question to be visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_set', models.ForeignKey(help_text='Question set this dependency belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='questionnaire.questionset')),
                ('dependent_question_set_question', models.ForeignKey(help_text='Question set question that depends on another', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='questionnaire.questionsetquestion')),
                ('source_question_set_question', models.ForeignKey(help_text='Question set question that the dependent question depends on', on_delete=django.db.models.deletion.CASCADE, related_name='dependent_questions', to='questionnaire.questionsetquestion')),
            ],
            options={
                'verbose_name': 'Dependency',
                'verbose_name_plural': 'Dependencies',
                'unique_together': {('question_set', 'dependent_question_set_question', 'source_question_set_question')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('number_answer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('boolean_answer', models.BooleanField(blank=True, null=True)),
                ('json_answer', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who provided this answer', on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_answers', to=settings.AUTH_USER_MODEL)),
                ('question_set_question', models.ForeignKey(help_text='Question set question this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.questionsetquestion')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'unique_together': {('question_set_question', 'user')},
            },
        ),
    ]
