# Generated by Django 5.1.11 on 2025-07-14 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoFormAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_id', models.CharField(max_length=100)),
                ('question_id', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mongo Form Answer',
                'verbose_name_plural': 'Mongo Form Answers',
                'unique_together': {('form_id', 'question_id', 'user')},
            },
        ),
    ]
